import bcrypt from "bcrypt";

const data = {
	users: [
		{
			name: "Leia",
			email: "admin@gmail.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: true,
		},
		{
			name: "dude",
			email: "dude@gmail.com",
			password: bcrypt.hashSync("1234", 8),
			isAdmin: false,
		},
	],
	products: [
		{
			name: "Dried Beef Liver",
			category: "Dried treats",
			image: "/images/beefliver.png",
			price: 20,
			countInStock: 10,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Sweet Potato Fries",
			category: "Dried treats",
			image: "/images/sweetPotato.jpg",
			price: 40,
			countInStock: 10,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Peanut Butter Biscuits",
			category: "Dried treats",
			image: "/images/peanut.jpg",
			price: 20,
			countInStock: 10,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Raw Hide",
			category: "Dried treats",
			image: "/images/rawhide.jpg",
			price: 20,
			countInStock: 0,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Dental Treats",
			category: "Dried treats",
			image: "/images/dental.jpg",
			price: 20,
			countInStock: 10,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
		{
			name: "Salmon Filets",
			category: "Dried treats",
			image: "/images/salmon.jpg",
			price: 20,
			countInStock: 10,
			brand: "Homemade",
			rating: 5,
			numReviews: 10,
			description: "High quality product",
		},
	],
};
export default data;
